input:
  generate:
    mapping: id = ksuid()
    count: 1000
    interval: ""

pipeline:
  processors:
    - while:
        at_least_once: true
        check: errored()
        max_loops: 100
        processors:
          - nats_kv:
              urls: [nats://localhost:4222]
              bucket: foo
              key: jeremy
              operation: get

          - catch:
              - log:
                  level: DEBUG
                  message: "${!error()}"

          - mapping: count = (count | 0) + 1

          - switch:
              - check: "@nats_kv_revision != null"
                processors:
                  - nats_kv:
                      urls: [nats://localhost:4222]
                      bucket: foo
                      key: jeremy
                      operation: update
                      revision: ${! @nats_kv_revision }

              - processors:
                  - nats_kv:
                      urls: [nats://localhost:4222]
                      bucket: foo
                      key: jeremy
                      operation: create
