input:
  nats_jetstream:
    urls: [nats://localhost:4222]
    subject: ratings

pipeline:
  threads: 12
  processors:
    - label: look_up_customer
      branch:
        processors:
          - sql_select:
              driver: "sqlite"
              dsn: "database.db"
              table: customers
              columns: ["*"]
              where: id = ?
              args_mapping: |-
                [customer_id]
        result_map: meta customer = this.index(0)

    - label: look_up_media
      branch:
        processors:
          - nats_kv:
              urls: [nats://localhost:4222]
              operation: get
              bucket: media
              key: ${! media_id }
          - catch: []
        result_map: meta media = this

    - label: update_media_rating
      nats_kv_update:
        urls: [nats://localhost:4222]
        bucket: media_ratings
        key: ${! @media.id }
        mutation: |
          value.title = @media.title
          value.poster = @media.omdb_result.poster
          value.avg = value.avg|0
          value.count = value.count|0
          value.avg = ((value.count * value.avg) + rating|0) / (value.count + 1)
          value.count = value.count + 1

output:
  switch:
    cases:
      - check: "!errored()"
        output:
          drop: {}
      - output:
          reject: "NACKing due to error: ${! error() }"
