input:
  aws_s3:
    bucket: codegangsta-media
    region: us-east-1
    scanner:
      csv: {}

pipeline:
  threads: 12
  processors:
    - branch:
        processors:
          - http:
              url: "http://www.omdbapi.com/?i=${! imdb_id }&apikey=${OMDB_API_KEY}"
        result_map: "omdb_result = this.map_each_key(key -> key.slug())"

output:
  nats_kv:
    urls: [nats://localhost:4222]
    bucket: media
    key: ${! id }
