services:
  na_1:
    image: nats
    command: -c /etc/my-server.conf --name na_1 -p 4222
    volumes:
      - ./server.conf:/etc/my-server.conf
    ports:
      - 4222:4222
  na_2:
    image: nats
    command: -c /etc/my-server.conf --name na_2 -p 4223
    volumes:
      - ./server.conf:/etc/my-server.conf
    ports:
      - 4223:4223
  na_3:
    image: nats
    command: -c /etc/my-server.conf --name na_3 -p 4224
    volumes:
      - ./server.conf:/etc/my-server.conf
    ports:
      - 4224:4224
