
server_name: yo
jetstream {
}
no_auth_user: alex
accounts {
  ACC: {
    jetstream {
        max_streams: 25
    }
    users = [
      {user: alex, password: not_needed}
    ]
  }
  $SYS: {
    users = [
      {user: system, password: s3cret}
    ]
  }
}


cluster: {
  name: NA,
  port: 6222,
  routes: [
    "nats://na_1:6222"
  ]
}
